import { Dynasty, DynastyEra } from "./components/app/model";

export const dynasties: Dynasty[] = [
    {
        id: 'xia',
        name: 'Xia Dynasty',
        era: DynastyEra.Ancient,
        eraIndex: 0,
        founder: { name: 'Yu the Great', avatar: '/img/xia.jpg' },
        capital: 'Erlitou (traditional)',
        facts: ['Earliest traditional dynasty', 'Flood control legend', 'Possibly semi-mythical'],
        start: -2070,
        end: -1600,
        followedBy: 'shang',
    },
    {
        id: 'shang',
        name: 'Shang Dynasty',
        era: DynastyEra.Ancient,
        eraIndex: 0,
        founder: { name: 'Tang of Shang', avatar: '/img/shang.jpg' },
        capital: 'Yin (Anyang)',
        facts: ['Oracle bone writing', 'Bronze technology', 'Early Chinese state'],
        start: -1600,
        end: -1046,
        precededBy: 'xia',
        followedBy: 'zhou',
    },
    {
        id: 'zhou',
        name: 'Zhou Dynasty',
        era: DynastyEra.Ancient,
        eraIndex: 0,
        founder: { name: 'King Wu of Zhou', avatar: '/img/zhou.jpg' },
        capital: 'Haojing / Luoyang',
        facts: ['Mandate of Heaven', 'Feudal system', 'Philosophical foundations'],
        start: -1046,
        end: -256,
        precededBy: 'shang',
        followedBy: 'qin',
    },

    {
        id: 'qin',
        name: 'Qin Dynasty',
        era: DynastyEra.Imperial,
        eraIndex: 1,
        founder: { name: 'Qin Shi Huang', avatar: '/img/qin.jpg' },
        capital: 'Xianyang',
        facts: ['First unified empire', 'Legalist rule', 'Standardization reforms'],
        start: -221,
        end: -206,
        precededBy: 'zhou',
        followedBy: 'han',
    },
    {
        id: 'han',
        name: 'Han Dynasty',
        era: DynastyEra.Imperial,
        eraIndex: 1,
        founder: { name: 'Liu Bang', avatar: '/img/han.jpg' },
        capital: "Chang’an / Luoyang",
        facts: ['Confucian state ideology', 'Silk Road expansion', 'Long stability'],
        start: -206,
        end: 220,
        precededBy: 'qin',
        followedBy: 'three-kingdoms',
    },

    {
        id: 'three-kingdoms',
        name: 'Three Kingdoms',
        era: DynastyEra.Division,
        eraIndex: 2,
        founder: { name: 'Cao Pi / Liu Bei / Sun Quan', avatar: '/img/3k.jpg' },
        capital: 'Luoyang / Chengdu / Jianye',
        facts: ['Wei Shu Wu division', 'Constant warfare', 'Famous historical romances'],
        start: 220,
        end: 280,
        precededBy: 'han',
        followedBy: 'jin',
    },
    {
        id: 'jin',
        name: 'Jin Dynasty',
        era: DynastyEra.Division,
        eraIndex: 2,
        founder: { name: 'Sima Yan', avatar: '/img/jin.jpg' },
        capital: 'Luoyang / Jiankang',
        facts: ['Brief reunification', 'Internal conflict', 'Northern invasions'],
        start: 266,
        end: 420,
        precededBy: 'three-kingdoms',
        followedBy: 'northern-southern',
    },
    {
        id: 'northern-southern',
        name: 'Northern and Southern Dynasties',
        era: DynastyEra.Division,
        eraIndex: 2,
        founder: { name: 'Various', avatar: '/img/ns.jpg' },
        capital: 'Multiple',
        facts: ['North-south division', 'Cultural exchange', 'Spread of Buddhism'],
        start: 420,
        end: 589,
        precededBy: 'jin',
        followedBy: 'sui',
    },

    {
        id: 'sui',
        name: 'Sui Dynasty',
        era: DynastyEra.Reunification,
        eraIndex: 3,
        founder: { name: 'Yang Jian', avatar: '/img/sui.jpg' },
        capital: 'Daxing (Xi’an)',
        facts: ['Reunified China', 'Grand Canal built', 'Short-lived'],
        start: 581,
        end: 618,
        precededBy: 'northern-southern',
        followedBy: 'tang',
    },
    {
        id: 'tang',
        name: 'Tang Dynasty',
        era: DynastyEra.Reunification,
        eraIndex: 3,
        founder: { name: 'Li Yuan', avatar: '/img/tang.jpg' },
        capital: "Chang’an",
        facts: ['Golden age', 'Cosmopolitan culture', 'Trade expansion'],
        start: 618,
        end: 907,
        precededBy: 'sui',
        followedBy: 'five-dynasties',
    },

    {
        id: 'five-dynasties',
        name: 'Five Dynasties and Ten Kingdoms',
        era: DynastyEra.Fragmentation,
        eraIndex: 4,
        founder: { name: 'Various', avatar: '/img/5d.jpg' },
        capital: 'Multiple',
        facts: ['Fragmentation', 'Regional rule', 'Transition period'],
        start: 907,
        end: 960,
        precededBy: 'tang',
        followedBy: 'song',
    },

    {
        id: 'song',
        name: 'Song Dynasty',
        era: DynastyEra.LaterImperial,
        eraIndex: 5,
        founder: { name: 'Zhao Kuangyin', avatar: '/img/song.jpg' },
        capital: 'Kaifeng / Hangzhou',
        facts: ['Economic boom', 'Technological innovation', 'Weak military'],
        start: 960,
        end: 1279,
        precededBy: 'five-dynasties',
        followedBy: 'yuan',
    },
    {
        id: 'yuan',
        name: 'Yuan Dynasty',
        era: DynastyEra.LaterImperial,
        eraIndex: 5,
        founder: { name: 'Kublai Khan', avatar: '/img/yuan.jpg' },
        capital: 'Dadu (Beijing)',
        facts: ['Mongol rule', 'Unified vast empire', 'Foreign influence'],
        start: 1271,
        end: 1368,
        precededBy: 'song',
        followedBy: 'ming',
    },
    {
        id: 'ming',
        name: 'Ming Dynasty',
        era: DynastyEra.LaterImperial,
        eraIndex: 5,
        founder: { name: 'Zhu Yuanzhang', avatar: '/img/ming.jpg' },
        capital: 'Nanjing / Beijing',
        facts: ['Restored Han rule', 'Great Wall expansion', 'Naval expeditions'],
        start: 1368,
        end: 1644,
        precededBy: 'yuan',
        followedBy: 'qing',
    },
    {
        id: 'qing',
        name: 'Qing Dynasty',
        era: DynastyEra.LaterImperial,
        eraIndex: 5,
        founder: { name: 'Hong Taiji', avatar: '/img/qing.jpg' },
        capital: 'Beijing',
        facts: ['Last dynasty', 'Territorial peak', 'Decline under pressure'],
        start: 1644,
        end: 1912,
        precededBy: 'ming',
        followedBy: 'republic',
    },
    {
        id: 'republic',
        name: 'Republic of China',
        era: DynastyEra.PostImperial,
        eraIndex: 6,
        founder: { name: 'Sun Yat-sen', avatar: '/img/roc.jpg' },
        capital: 'Nanjing',
        facts: ['End of imperial rule', 'Political instability', 'Civil war period'],
        start: 1912,
        end: 1949,
        precededBy: 'qing',
        followedBy: 'prc',
    },
    {
        id: 'prc',
        name: "People’s Republic of China",
        era: DynastyEra.PostImperial,
        eraIndex: 6,
        founder: { name: 'Mao Zedong', avatar: '/img/prc.jpg' },
        capital: 'Beijing',
        facts: ['Communist state', 'Modern China', 'Rapid development'],
        start: 1949,
        end: new Date().getFullYear(),
        precededBy: 'republic',
    },
];